### ISSUE TITLE
TypeScript support

### ISSUE THREAD

**Issue by turneand** [autotelic/fastify-opentelemetry#20]
Great library, looking to use it in some of our existing applications.

However, we're all TypeScript so was wondering if you'd be interested in adding a types file, or migrating the app in its entirety over to typescript?  More than happy to contribute a PR if you have a preference.

**Comment by HW13** [comment]
Hey, thanks @turneand!

I think the preference right now would be adding a types file rather than a complete migration. If you'd be willing to submit a PR for that, it would be much appreciated. 🙏

**Comment by JacobMGEvans** [comment]
Greetings,
If you change your mind about a complete migration feel free to contact us as well 😄. If you are interested we can "Raid" your repository, there would be one big PR from our Organization, for a large specific task/problem domain; in this case TS conversion.

We would need a maintainer as a point of contact, we prefer using Discord https://discord.gg/xkdkAJZsBR

Let me know if you are interested.
You can read more about what we are doing here: https://github.com/OpenSourceRaidGuild/tutorial-quest
This is also an example of how we work and the workflow: HospitalRun/hospitalrun-frontend#2516

cc: @nobrayner @mpeyper @Aprillion

**Comment by HW13** [comment]
Thanks @JacobMGEvans, appreciate the offer! We'll keep that in mind if we decide to migrate in the future 👍
