### ISSUE TITLE
Is a context manager really necessary?

### ISSUE THREAD

**Issue by carlpett** [autotelic/fastify-opentelemetry#31]
In the readme, there's a comment in the example claiming that wrap routes requires having a context manager:
https://github.com/autotelic/fastify-opentelemetry/blob/15f12ebbc9d14a841e81589a6fd873ec65aeb3c6/README.md#L72-L76

Now, it seems there's a bug here, [you need to call `enable()` on the context manager](https://github.com/open-telemetry/opentelemetry-js/issues/1405). Otherwise the parent span got lost after `await`:ing in handlers. But after finding that out, I saw references in upstream release notes that another context manager is automatically used if not manually installed. And simply removing `AsyncHooksContextManager` altogether _seems_ to also get things working...

Is the comment outdated, or is there something I'm not seeing yet?

**Comment by HW13** [comment]
Hi @carlpett, thanks for opening an issue!

I can confirm that a context manager is still required in order for `wrapRoutes` to function properly. When running the [example app](https://github.com/autotelic/fastify-opentelemetry/tree/main/example), if you comment out [this line](https://github.com/autotelic/fastify-opentelemetry/blob/15f12ebbc9d14a841e81589a6fd873ec65aeb3c6/example/opentelemetry.js#L16) and make a request - the `'reply.doingWork'` span will have an `undefined` `parentId`. With the line not commented out the `parentId` will be correct. 

If using the[ `NodeTracerProvider`](https://github.com/open-telemetry/opentelemetry-js/tree/main/packages/opentelemetry-node#opentelemetry-node-sdk), it will automatically provide a context manager (either [`AsyncHooksContextManager`](https://github.com/open-telemetry/opentelemetry-js/blob/main/packages/opentelemetry-context-async-hooks/src/AsyncHooksContextManager.ts) or [`AsyncLocalStorageContextManager`](https://github.com/open-telemetry/opentelemetry-js/blob/main/packages/opentelemetry-context-async-hooks/src/AsyncLocalStorageContextManager.ts) depending on your node version - [see here](https://github.com/open-telemetry/opentelemetry-js/blob/082abf9736aa58c45379cc5541118c4bcb9969a0/packages/opentelemetry-node/src/NodeTracerProvider.ts#L60)). However, the [`BasicTracerProvider`](https://github.com/open-telemetry/opentelemetry-js/blob/main/packages/opentelemetry-tracing/src/BasicTracerProvider.ts) used in the example will not provide a default context manager, and you'll end up with the `context` API's [noop default](https://github.com/open-telemetry/opentelemetry-js-api/blob/c595a59770d6dc30110bd9412d613ea20c25c654/src/api/context.ts#L90).

Good catch with the missing `enable()` in the examples, would you like to create a PR to fix them?

**Comment by carlpett** [comment]
Ah, I am indeed using the `NodeTraceProvider`, that explains why it is working :) 
I'm out of office for the rest of the week, but can try to have a look at it later.

**Comment by HW13** [comment]
I've gone ahead and updated our examples, thanks for bringing this to our attention @carlpett! 😎 👍
