### ISSUE TITLE
Support ignoreMethods

### ISSUE THREAD

**Issue by JosephScript** [autotelic/fastify-opentelemetry#38]
I want to be able to block certain request methods from being traced. For example to prevent `option` requests:

```js
app.register(fastifyOpentelemetry, { 
   serviceName: 'my-app', 
   wrapRoutes: true,
   ignoreMethods: ['options']
})
```

Is something like this possible? If not could it be implemented?

**Comment by HW13** [comment]
That makes sense to me, thanks @JosephScript 👍 

I think a little more flexibility with our `ignoreRoutes` option should do the trick.

I've just opened a PR(#39) which updates the `ignoreRoutes` option to also accept a function that receives the path and method, then returns a boolean.

So to ignore all OPTIONS routes:
```js
app.register(fastifyOpentelemetry, { 
   serviceName: 'my-app', 
   wrapRoutes: true,
   ignoreRoutes: (path, method) => method === 'OPTIONS'
})
```
