### ISSUE TITLE
Easy access to TraceId

### ISSUE THREAD

**Issue by pierlucg-xs** [autotelic/fastify-opentelemetry#42]
I would like to log the traceId in all logs where it is available, the easiest way I found to get the traceId is the following:
```ts
const traceId = req.openTelemetry().activeSpan?.spanContext().traceId;
```

which is not very elegant. Is there a better way and if not, would it be a good idea for this plugin to decorate the request with the traceId?

**Comment by HW13** [comment]
Unfortunately things can get pretty nested. I think providing easier access to the traceId sounds like a good idea.

What did you have in mind? A top level request decorator (`request.traceId`), or adding a property to the `openTelemetry` decorator (`request.openTelemetry().traceId`)?

If you don't mind opening a PR, we're always open to ideas 🙂

**Comment by HW13** [comment]
Closing, as the issue/PR has gone stale
