### ISSUE TITLE
fastify v4 support

### ISSUE THREAD

**Issue by vidarc** [autotelic/fastify-opentelemetry#46]
https://www.fastify.io/docs/latest/Migration-Guide-V4/

If there are no deprecation warnings, I haven't seen any from this package, the migration should be as simple as bumping this: https://github.com/autotelic/fastify-opentelemetry/blob/main/index.js#L158

**Comment by HW13** [comment]
Fastify v4 support is live in v0.17.0 (Thanks @gjuchault!) 🚀
