### ISSUE TITLE
`serviceName` in plugin config

### ISSUE THREAD

**Issue by alphaone** [autotelic/fastify-opentelemetry#52]
Hey,

First, I want to thank you for working on this library. It is very much appreciated 🙏 

Looking at the [example](https://github.com/autotelic/fastify-opentelemetry/blob/3ac394d0ddac6cd68d0aa0c54b57d0e4df5200c8/example/index.js#L11) I can see :

```
  await fastify.register(fastifyOpentelemetry, { serviceName: 'basic-example', wrapRoutes: true })
```

When I try to use `serviceName` as an config option in my code I get an error, that `serviceName` is not supported as an option:
`Object literal may only specify known properties, and 'serviceName' does not exist in type 'FastifyRegisterOptions<OpenTelemetryPluginOptions>'.`

I was wondering, if this option was removed or is only planned for future releases 🤔

**Comment by SeanReece** [comment]
Also noticed the same thing. Looks like it was removed https://github.com/autotelic/fastify-opentelemetry/pull/41#issue-954735408
