### ISSUE TITLE
PreValidation-handlers are reported outside of the request-span

### ISSUE THREAD

**Issue by marcus13371337** [autotelic/fastify-opentelemetry#56]
Hi,

Thanks for this great library!

I've a problem that our "preValidation"-handlers for our routes seem to be reported under their own spans instead of a child-span to the route. Is that a bug or am I doing something wrong?

**Comment by HW13** [comment]
Hi @marcus13371337,

We're only able to automatically wrap route handlers in the request span's context. To do this we use Fastify's [`onRoute` hook](https://www.fastify.io/docs/latest/Reference/Hooks/#onroute). Unfortunately there currently isn't a way for us to do the same for hooks (we'd need an "onHook" hook). However, our request decorator does expose the request span's context, which can be passed into `tracer.startSpan` - the resulting span will be a child of the request span.

```js
fastify.addHook('preValidation', async function preValidationHook (request) {
  const { tracer, context } = request.openTelemetry()
  const span = tracer.startSpan('preValidation', undefined, context)
  // Do stuff...
  span.end()
})
```

I'm now realizing that we should probably document usage within hooks, so thanks for bringing this to our attention!

**Comment by marcus13371337** [comment]
Wouldn't it be possible to do something similar to [this](https://www.fastify.io/docs/latest/Reference/Hooks/#onroute) (similar to what you do in this library as well)
```ts
fastify.addHook('onRoute', (routeOptions) => {
  routeOptions.preParsing = routeOptions.preParsing.map(handler => wrapHandler(handler));
  routeOptions.preValidation = routeOptions.preValidation.map(handler => wrapHandler(handler));
  routeOptions.preHandler = routeOptions.preHandler.map(handler => wrapHandler(handler));
  routeOptions.preSerialization = routeOptions.preSerialization.map(handler => wrapHandler(handler));
  routeOptions.onSend = routeOptions.onSend.map(handler => wrapHandler(handler));
})
```

**Comment by HW13** [comment]
Oh yeah, we could totally do something like that. Good call 😎 
Any chance you'd be able to implement in a PR @marcus13371337?

**Comment by marcus13371337** [comment]
@HW13 Sure sounds like a fun problem to solve! However, I question before I start, what do you think is the optimal "span-setup"?

*The same span in all handlers*
1. onRequst - start "GET /xxx"-span
2. preParsing -> wrap with same span
3. ...
4. onResponse -> close span

Or *a child span per handler*:
1. onRequst - start "GET /xxx"-span
2. preParsing -> wrap with a child span "preParsing"
3. ...
4. onResponse -> close span

?

**Comment by HW13** [comment]
Awesome, thanks @marcus13371337!

In terms of setup, we would want to handle this within our `wrapRoutes` logic. So each handler would be wrapped in `context.with` and use the onRequest span's context. In fact, we could use the existing [`wrapRoute`](https://github.com/autotelic/fastify-opentelemetry/blob/41dfdb788acbb83733052cf0cfe5060e8ad677ae/index.js#L137) function (maybe rename it `wrapHandler` though). We don't want to start any child spans, that can be left up to individual implementation.
