### ISSUE TITLE
span.kind should be set to server

### ISSUE THREAD

**Issue by mmunte-impeo** [autotelic/fastify-opentelemetry#69]
Hello, 

great library!

I believe the span kind should be always set to server. Currently, as no params are used, kind internal is probably used.

`    const span = tracer.startSpan(
      formatSpanName(request),
      {},
      activeContext
    )`

**Comment by HW13** [comment]
Thanks @mmunte-impeo! Would you like to open a PR updating this value?

**Comment by HW13** [comment]
Hi @mmunte-impeo, just opened a PR which will allow the span options to be configurable with the default options setting span kind to server -> #73 👍
